- name: variables
  hosts: localhost
  vars:
   Course: "Terraform"
   Trainer: "Siva"
   Duration: "15hrs"
  tasks:
  - name: print override information
    vars:
     Course: "DevOps"  
    ansible.builtin.debug:
     msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."

  - name: print information
    ansible.builtin.debug:
     msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."